#!/bin/bash
printf "\n>checking schedule \n"
curl --get 'http://172.17.0.2:8080/schedule' -d "from=2022-05-22@10:00:00&to=2022-05-30@12:00:00"
printf "\n>checking screening data \n" 
curl --get 'http://172.17.0.2:8080/screening/2'
printf "\n>reserving seats \n"
curl -X POST 'http://172.17.0.2:8080/screening/2' -d "Wojtek;Pak;18;C;19;D;20;S"
