#!/bin/bash

mysql cinema_db -e "insert into movie(duration,name) 
values('01:30:00','poranek kojota');"

mysql cinema_db -e "insert into movie(duration,name) 
values('01:30:00','film 2');"

mysql cinema_db -e "insert into room(row_quantity,row_length,number)
values(10,4,10);"

mysql cinema_db -e "insert into room(row_quantity,row_length,number)
values(10,10,10);"

mysql cinema_db -e "insert into screening(starting_time,movie_id,room_id)
values ('2022-05-05 12:00:00',1,1);"

mysql cinema_db -e "insert into screening(starting_time,movie_id,room_id)
values ('2022-05-28 13:00:00',1,1);"

mysql cinema_db -e "insert into screening(starting_time,movie_id,room_id)
values ('2022-05-31 16:00:00',2,2);"

mysql cinema_db -e "insert into reservation_info(name,surname,expiration)
values ('Adam','Kowalski','2022-05-05 06:00:00');"

mysql cinema_db -e "insert into reservation(seat_no,type,reservation_info_id,screening_id)
values (0,'C',1,1);"
